# Schema for the configuration files of the Live weather module.

live_weather.settings:
  type: config_object
  label: 'Live weather settings'
  mapping:
    settings:
      type: mapping
      label: 'Live weather settings'
      mapping:
        unit:
          type: string
          label: 'Temperature unit'
        image:
          type: boolean
          label: 'Forcast Image'
        wind:
          type: boolean
          label: 'Wind speed'
        humidity:
          type: boolean
          label: 'Humidity level'
        visibility:
          type: boolean
          label: 'Visibility level'
        sunrise: 
          type: boolean
          label: 'Sunrise time'
        sunset:
          type : boolean
          label: 'Sunset time'
        cache:
          type: integer
          label: 'Cache settings'
